# Pipeline con Gradle, JaCoCo y SonarCloud, pero creado con el wizard de Azure Pipelines

pool:
  name: Azure Pipelines

variables:
  Parameters.wrapperScript: 'gradlew'
  Parameters.tasks: 'clean test build'

steps:
  - task: SonarQubePrepare@5
    displayName: 'Prepare analysis on SonarQube'
    inputs:
      SonarQube: SonarCloud
      scannerMode: Other

  - task: Gradle@3
    displayName: 'gradlew clean test build'
    inputs:
      gradleWrapperFile: '$(Parameters.wrapperScript)'
      tasks: '$(Parameters.tasks)'
      codeCoverageToolOption: JaCoCo
      sonarQubeRunAnalysis: true
      sqGradlePluginVersionChoice: build

  - task: SonarQubePublish@5
    displayName: 'Publish Quality Gate Result'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**/*.jar'
      TargetFolder: '$(build.artifactstagingdirectory)'
    enabled: true
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
    enabled: true
    condition: succeededOrFailed()