# Pipeline con Gradle, JaCoCo y SonarCloud, pero creado con el wizard de Azure Pipelines

pool:
  name: Azure Pipelines

variables:
  Parameters.wrapperScript: 'gradlew'
  Parameters.tasks: 'clean test build'

steps:
  - task: SonarSource.sonarqube.15B84CA1-B62F-4A2A-A403-89B77A063157.SonarQubePrepare@5
    displayName: 'Prepare analysis on SonarQube'
    inputs:
      SonarQube: SonarCloud
      scannerMode: Other

  - task: Gradle@3
    displayName: 'gradlew clean test build'
    inputs:
      gradleWrapperFile: '$(Parameters.wrapperScript)'
      tasks: '$(Parameters.tasks)'
      codeCoverageToolOption: JaCoCo
      sonarQubeRunAnalysis: true
      sqGradlePluginVersionChoice: build

  - task: SonarSource.sonarqube.291ed61f-1ee4-45d3-b1b0-bf822d9095ef.SonarQubePublish@5
    displayName: 'Publish Quality Gate Result'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**/*.jar'
      TargetFolder: '$(build.artifactstagingdirectory)'
    enabled: true
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
    enabled: true
    condition: succeededOrFailed()